stages:
  - build

services:
  - docker:dind

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

build:
  image: docker
  stage: build
  before_script:
    - DOCKER_BUILDKIT=1
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
