version: "3"

services:
  api:
    build:
      context: .
    links:
      - postgres
      - mongo
    ports:
      - 8081:8081
    environment:
      DB_HOST: postgres
      SECURE_COOKIE: 'false'
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
