version: "3"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: [--auth]
